// Offline integration proof with explicit fixture scores; never reported as a live AI ad.
import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';import {synthesizeScore} from './sound-design.mjs';import {durationOf} from './schema.mjs';
const require=createRequire(import.meta.url),{renderPreviews}=require('../Questera-Backend/motion/previews.cjs'),{bundle}=require('@remotion/bundler'),{selectComposition,renderMedia}=require('@remotion/renderer');
const dir=path.resolve('.motion-proof/automatic-flow');await fs.mkdir(dir,{recursive:true});
const base='http://127.0.0.1:4701/api/motion',{token}=await(await fetch(base+'/local-session',{method:'POST',headers:{'X-Motion-Local':'1'}})).json();const api=async(route,method='GET',body)=>{const response=await fetch(base+route,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const r=await response.json();if(!response.ok)throw Error(r.error);return r;};
const project=JSON.parse(await fs.readFile('.motion-proof/velos-ads/v3/06-words-that-move.json','utf8')),assets=(await api('/assets')).assets,urls=Object.fromEntries(assets.map(a=>[a.id,a.url]));
const images=await renderPreviews({project,urls});for(const image of images)await fs.writeFile(path.join(dir,`preview-${image.frame}.jpg`),Buffer.from(image.dataUrl.split(',')[1],'base64'));
const frames=durationOf(project),notes=[];for(let frame=0,i=0;frame<frames-15;frame+=15,i++){notes.push({frame,duration:Math.min(30,frames-frame),midi:[48,55,60,63,67,72,67,63][i%8],voice:i%4===0?'bass':'pluck',velocity:i%4===0?.7:.4});if(i%2===0)notes.push({frame,duration:6,midi:60,voice:'kick',velocity:.5});if(i%4===2)notes.push({frame,duration:6,midi:60,voice:'snare',velocity:.3});}
const plan={mode:'generated',name:'Integration fixture score',assetId:null,tempo:120,seed:123,notes},sound=synthesizeScore(plan,frames);await fs.writeFile(path.join(dir,'score-a.wav'),sound.buffer);const alternative={...plan,seed:317,notes:notes.map(n=>({...n,midi:n.midi+4,voice:n.voice==='pluck'?'chime':n.voice}))};await fs.writeFile(path.join(dir,'score-b.wav'),synthesizeScore(alternative,frames).buffer);
const audio=await api('/assets','POST',{name:'Integration fixture score',mimeType:'audio/wav',data:sound.buffer.toString('base64')});urls[audio.id]=audio.url;project.audio=[{id:'fixture-track',assetId:audio.id,name:'Integration fixture score',start:0,trim:0,duration:frames,volume:.85,fade:6}];
const serveUrl=await bundle({entryPoint:path.resolve('motion/entry.jsx'),publicDir:path.resolve('public')}),inputProps={project,urls},composition=await selectComposition({serveUrl,id:'VelosMotion',inputProps});await renderMedia({serveUrl,composition,inputProps,codec:'h264',outputLocation:path.join(dir,'integration-fixture.mp4'),concurrency:2});
await fs.writeFile(path.join(dir,'proof.json'),JSON.stringify({method:'Offline integration fixture; visuals use the preserved v3 ad, scores are test data. This is not a new AI generation or a creative-quality benchmark.',previews:images.map(({dataUrl,...im})=>im),sound:{frames,notes:notes.length,peak:sound.peak,audioAssetId:audio.id},file:'integration-fixture.mp4'},null,2));console.log(JSON.stringify({previewFrames:images.length,generatedScoreNotes:notes.length,peak:sound.peak,fixture:path.join(dir,'integration-fixture.mp4')}));
