import fs from 'node:fs/promises';import path from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
const run=promisify(execFile);const batch=process.argv.find(a=>a.startsWith('--batch='))?.split('=')[1]||'v3';if(!/^v[23]$/.test(batch))throw Error('Choose batch v2 or v3.');const dir=path.resolve(`.motion-proof/velos-ads/${batch}`);const report=JSON.parse(await fs.readFile(path.join(dir,'benchmark.json'),'utf8'));const checks=[];
for(const ad of report.ads.filter(a=>a.status==='rendered')){
 const file=path.join(dir,`${ad.slug}.mp4`),project=JSON.parse(await fs.readFile(path.join(dir,`${ad.slug}.json`),'utf8'));
 const {stdout}=await run('ffprobe',['-v','error','-show_entries','stream=codec_name,width,height,r_frame_rate,nb_frames,duration:format=duration,size','-of','json',file]);const media=JSON.parse(stdout);const video=media.streams.find(s=>s.codec_name==='h264'),audio=media.streams.find(s=>s.codec_name==='aac');
 const decode=await run('ffmpeg',['-v','error','-i',file,'-f','null','-']);const sound=await run('ffmpeg',['-i',file,'-af','volumedetect','-vn','-f','null','-']);
 for(const sample of ['early','settled'])await run('ffmpeg',['-y','-v','error','-pattern_type','glob','-i',path.join(dir,`${ad.slug}-shot-*-${sample}.png`),'-vf','scale=480:540:force_original_aspect_ratio=decrease,pad=480:540:(ow-iw)/2:(oh-ih)/2:color=0x16151a,tile=3x2','-frames:v','1',path.join(dir,`${ad.slug}-${sample}-review.jpg`)]);
 const result={slug:ad.slug,video,audio,bytes:Number(media.format.size),decodeErrors:decode.stderr,meanVolume:Number(sound.stderr.match(/mean_volume: ([-\d.]+)/)?.[1]),peakVolume:Number(sound.stderr.match(/max_volume: ([-\d.]+)/)?.[1]),scenes:project.scenes.length,layers:project.scenes.reduce((n,s)=>n+s.layers.length,0),keyframes:project.scenes.flatMap(s=>s.layers).reduce((n,l)=>n+l.keyframes.length,0),closingSeconds:project.scenes.at(-1).duration/30,valid:video?.width===ad.width&&video?.height===ad.height&&video?.r_frame_rate==='30/1'&&Number(video?.nb_frames)===ad.seconds*30&&!!audio&&!decode.stderr};checks.push(result);
}
await fs.writeFile(path.join(dir,'verification.json'),JSON.stringify(checks,null,2));console.log(JSON.stringify(checks.map(({slug,valid,meanVolume,peakVolume})=>({slug,valid,meanVolume,peakVolume}))));
