import React, { useEffect, useRef } from 'react';
import { motion } from 'framer-motion';
import * as FiIcons from 'react-icons/fi';
import SafeIcon from '../../common/SafeIcon';

const { FiUser, FiZap, FiDownload, FiRefreshCw, FiMoreHorizontal, FiCopy } = FiIcons;

const MessageList = ({ messages, loading }) => {
  const scrollRef = useRef(null);
  const bottomRef = useRef(null);

  useEffect(() => {
    if (bottomRef.current) {
        bottomRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [messages, loading]);

  const handleDownload = (url) => {
    const link = document.createElement('a');
    link.href = url;
    link.download = `velos-generated-${Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="h-full overflow-y-auto custom-scrollbar px-4 sm:px-8 py-8" ref={scrollRef}>
      <div className="max-w-4xl mx-auto flex flex-col gap-8 pb-32">
        
        {/* Empty State */}
        {messages.length === 0 && !loading && (
          <div className="h-[60vh] flex flex-col items-center justify-center text-center space-y-6 opacity-60">
            <div className="relative">
                <div className="absolute inset-0 bg-white/20 blur-xl rounded-full"></div>
                <div className="relative w-20 h-20 rounded-3xl bg-[#1c1c1e] flex items-center justify-center border border-white/10 shadow-2xl">
                    <span className="text-4xl">⚡</span>
                </div>
            </div>
            <div>
              <h3 className="text-2xl font-bold text-white tracking-tight">Velos Canvas</h3>
              <p className="text-zinc-400 text-base mt-2 max-w-sm mx-auto">
                Ready to visualize your ideas. Type a prompt below to start creating.
              </p>
            </div>
          </div>
        )}

        {messages.map((msg, idx) => (
          <motion.div
            key={idx}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, ease: "easeOut" }}
            className={`flex gap-6 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}
          >
            {/* Avatar */}
            <div className={`w-9 h-9 rounded-full flex items-center justify-center flex-shrink-0 shadow-lg mt-1 ${
              msg.role === 'user' 
                ? 'bg-zinc-800 text-zinc-400 border border-zinc-700' 
                : 'bg-white text-black border border-white'
            }`}>
              {msg.role === 'user' ? <SafeIcon icon={FiUser} className="w-4 h-4" /> : <SafeIcon icon={FiZap} className="w-4 h-4" />}
            </div>

            {/* Content Container */}
            <div className={`flex flex-col gap-3 max-w-[85%] lg:max-w-[70%] ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
              
              {/* Text Bubble */}
              {msg.content && (
                <div className={`relative px-6 py-4 rounded-3xl text-[15px] leading-relaxed shadow-sm backdrop-blur-sm group ${
                  msg.role === 'user' 
                    ? 'bg-[#27272a] text-zinc-100 border border-white/5 rounded-tr-sm' 
                    : 'bg-transparent text-zinc-300 pl-0 pt-1 border-none shadow-none'
                }`}>
                  {msg.content}
                </div>
              )}

              {/* Reference Images (User) */}
              {msg.role === 'user' && msg.referenceImages && msg.referenceImages.length > 0 && (
                 <div className="flex gap-2 p-1 bg-[#1c1c1e] rounded-2xl border border-white/5">
                   {msg.referenceImages.map((img, i) => (
                     <div key={i} className="w-16 h-16 rounded-xl overflow-hidden border border-white/5 relative group/img">
                       <img src={img} alt="Ref" className="w-full h-full object-cover" />
                     </div>
                   ))}
                 </div>
              )}

              {/* Generated Image (Assistant) */}
              {msg.role === 'assistant' && msg.imageUrl && (
                <div className="relative group rounded-3xl overflow-hidden border border-white/10 shadow-2xl bg-[#09090b] mt-2 transition-transform hover:scale-[1.01] duration-500">
                  <img 
                    src={msg.imageUrl} 
                    alt="Generated by Velos" 
                    className="max-w-full sm:max-w-lg h-auto object-cover block" 
                    loading="lazy"
                  />
                  
                  {/* Overlay Actions */}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-all duration-300 flex items-end justify-between p-6">
                    <div className="flex gap-3">
                       <button 
                        onClick={() => handleDownload(msg.imageUrl)}
                        className="flex items-center gap-2 px-4 py-2 bg-white text-black rounded-xl text-xs font-bold hover:bg-zinc-200 transition-colors shadow-lg" 
                       >
                         <SafeIcon icon={FiDownload} className="w-4 h-4" />
                         Download
                       </button>
                       <button className="p-2 bg-white/10 hover:bg-white/20 text-white backdrop-blur-md rounded-xl transition-all border border-white/10" title="Remix">
                         <SafeIcon icon={FiRefreshCw} className="w-4 h-4" />
                       </button>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </motion.div>
        ))}

        {/* Loading Indicator */}
        {loading && (
          <div className="flex gap-6">
             <div className="w-9 h-9 rounded-full bg-white text-black flex items-center justify-center flex-shrink-0 shadow-lg border border-white mt-1">
               <span className="animate-spin text-lg">⚡</span>
             </div>
             <div className="flex flex-col gap-3">
               <div className="flex items-center gap-2">
                   <div className="text-sm text-zinc-400 font-medium">Visualizing...</div>
               </div>
               <div className="flex gap-1.5 h-8 items-center pl-1">
                 <motion.div 
                   animate={{ height: [4, 16, 4], opacity: [0.5, 1, 0.5] }} 
                   transition={{ repeat: Infinity, duration: 1, ease: "easeInOut" }} 
                   className="w-1 bg-white rounded-full shadow-[0_0_10px_rgba(255,255,255,0.5)]" 
                 />
                 <motion.div 
                   animate={{ height: [4, 24, 4], opacity: [0.5, 1, 0.5] }} 
                   transition={{ repeat: Infinity, duration: 1, ease: "easeInOut", delay: 0.1 }} 
                   className="w-1 bg-white rounded-full shadow-[0_0_10px_rgba(255,255,255,0.5)]" 
                 />
                 <motion.div 
                   animate={{ height: [4, 16, 4], opacity: [0.5, 1, 0.5] }} 
                   transition={{ repeat: Infinity, duration: 1, ease: "easeInOut", delay: 0.2 }} 
                   className="w-1 bg-white rounded-full shadow-[0_0_10px_rgba(255,255,255,0.5)]" 
                 />
               </div>
             </div>
          </div>
        )}
        
        <div ref={bottomRef} className="h-1" />
      </div>
    </div>
  );
};

export default MessageList;