import test from 'node:test';import assert from 'node:assert/strict';import {MongoMemoryServer} from 'mongodb-memory-server';import {createRequire} from 'node:module';import crypto from 'node:crypto';
const require=createRequire(import.meta.url),mongoose=require('../Questera-Backend/node_modules/mongoose');const {MongoStore}=require('../Questera-Backend/motion/store.cjs');const {reserve,wallet}=require('../Questera-Backend/motion/worker.cjs');
test('real MongoDB: CAS saves, quota races, atomic credits, signed and replayed billing',async t=>{
 const db=await MongoMemoryServer.create();await mongoose.connect(db.getUri());t.after(async()=>{await mongoose.disconnect();await db.stop();});const store=new MongoStore();await store.Model.init();await store.create('project',{id:'project',userId:'alice',title:'one'});const attempts=await Promise.allSettled([store.mutate('project','project','alice',p=>({...p,title:'a'}),1),store.mutate('project','project','alice',p=>({...p,title:'b'}),1)]);assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);assert.equal(attempts.find(r=>r.status==='rejected').reason.status,409);assert.equal(await store.get('project','project','bob'),null);
 const w=await wallet(store,'alice');await store.mutate('usage',w.id,'alice',u=>({...u,limit:15}));const reservations=await Promise.allSettled(Array.from({length:8},(_,i)=>reserve(store,'alice',`r${i}`,15)));assert.equal(reservations.filter(r=>r.status==='fulfilled').length,1,JSON.stringify(reservations.map(r=>r.reason?.message||r.status)));
 process.env.RAZORPAY_KEY_ID='rzp_test_dummy';process.env.RAZORPAY_KEY_SECRET='dummy';const Credits=require('../Questera-Backend/models/credits');await Credits.init();const Controller=require('../Questera-Backend/functions/Credits');const c=new Controller();await c.getOrCreateCredits('credits-test');const charges=await Promise.all(Array.from({length:8},()=>c.deductCredits('credits-test',5)));assert.equal(charges.filter(r=>r.success).length,4);let record=await Credits.findOne({userId:'credits-test'});assert.equal(record.balance,0);assert.equal(record.totalCreditsUsed,20);assert.deepEqual(record.transactions.slice(1).map(t=>t.balanceAfter).sort((a,b)=>a-b),[0,5,10,15]);
 const start=new Date('2026-09-01'),end=new Date('2026-10-01');await Promise.all(Array.from({length:4},()=>c.handleSubscription('credits-test','growth','cust','sub',start,end)));record=await Credits.findOne({userId:'credits-test'});assert.equal(record.balance,100);assert.equal(record.processedGrants.length,1);assert.equal(record.transactions.filter(t=>t.type==='subscription').length,1);
 const raw=Buffer.from('{"event": "noop"}');const secret='billing-secret';const signature=crypto.createHmac('sha256',secret).update(raw).digest('hex');assert.equal(c.verifyWebhookSignature(raw,signature,secret),true);assert.equal(c.verifyWebhookSignature(Buffer.from('{"event":"noop"}'),signature,secret),false);process.env.RAZORPAY_WEBHOOK_SECRET=secret;assert.equal((await c.handleRazorpayWebhook({body:{event:'noop'},rawBody:raw,headers:{}})).status,400);assert.equal((await c.handleRazorpayWebhook({body:{event:'noop'},rawBody:raw,headers:{'x-razorpay-signature':signature}})).status,200);
});
