import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';
import {exampleProject,durationOf} from '../motion/schema.mjs';import {validateSoundPlan,synthesizeScore} from '../motion/sound-design.mjs';
const require=createRequire(import.meta.url),{automaticDesign,reviewDesign}=require('../Questera-Backend/motion/automatic.cjs'),{design}=require('../Questera-Backend/motion/design.cjs');
const sound={mode:'generated',name:'A rising idea',tempo:112,seed:471,assetId:null,notes:[{frame:0,duration:30,midi:48,velocity:.5,voice:'bass'},{frame:30,duration:40,midi:60,velocity:.5,voice:'pluck'},{frame:90,duration:60,midi:67,velocity:.5,voice:'pad'},{frame:390,duration:30,midi:72,velocity:.5,voice:'chime'}]};
const criteria={hook:9,proof:9,motion:9,readability:9,brand:9,ending:9};
const usage={total_tokens:100,prompt_tokens:60,completion_tokens:40,cost:.01};
const result=()=>({project:exampleProject(),summary:'Original fixture for workflow testing',usage,attempts:1,model:'google/gemini-3.8-flash'});
test('automatic generation renders, critiques, repairs and accounts every provider call without selecting layouts',async()=>{
 let generated=0,rendered=0,reviewed=0;const args={brief:'Make an original 15-second Velos ad',assets:[],format:'landscape'};
 const r=await automaticDesign(args,{generate:async a=>{generated++;assert.equal(a.pipeline,'freeform');if(generated===1)assert.equal(a.project,null);else{assert.match(a.feedback,/headline/);assert.equal(a.mode,'edit');}return result();},preview:async({project})=>{rendered++;assert.equal(durationOf(project),450);return [{sceneId:project.scenes[0].id,frame:35,sample:'early',dataUrl:'data:image/jpeg;base64,fixture'}];},review:async()=>{reviewed++;return {approved:reviewed===2,score:reviewed===2?9:5,issues:reviewed===2?[]:['Move the clipped headline into the canvas.'],summary:'Frame review',soundPlan:sound,usage,attempts:1,model:'google/gemini-3.8-flash'};}});
 assert.equal(generated,2);assert.equal(rendered,2);assert.equal(r.automation.passes.length,2);assert.equal(r.pipeline,'automatic');assert.equal(r.attempts,4);assert.equal(r.usage.total_tokens,400);assert.equal(r.usage.cost,.04);assert.equal(r.appTitle,'Greta');assert.equal(r.automation.passes[0].frames[0].dataUrl,undefined);
});
test('automatic flow fails closed after two rejected reviews and never substitutes a template',async()=>{
 let calls=0;await assert.rejects(()=>automaticDesign({brief:'An ad',assets:[],format:'square'},{generate:async()=>{calls++;return result();},preview:async()=>[],review:async()=>({approved:false,score:3,issues:['Unreadable CTA'],summary:'Needs work',soundPlan:sound,usage,attempts:1})}),e=>e.status===422&&/Unreadable CTA/.test(e.message));assert.equal(calls,2);
});
test('an expired automatic deadline makes no provider call',async()=>{let calls=0;await assert.rejects(()=>automaticDesign({brief:'An ad',assets:[],deadline:Date.now()-1},{generate:async()=>{calls++;return result();}}),e=>e.status===504);assert.equal(calls,0);});
test('default create uses raw geometry, image-based review, Gemini 3.8 and Greta',async t=>{
 const previews=require('../Questera-Backend/motion/previews.cjs'),oldPreview=previews.renderPreviews,oldFetch=globalThis.fetch,oldKey=process.env.OPENROUTER_API_KEY;process.env.OPENROUTER_API_KEY='test-key';previews.renderPreviews=async()=>[{sceneId:'fixture',scene:'Hook',frame:35,sample:'settled',dataUrl:'data:image/jpeg;base64,Zml4dHVyZQ=='}];t.after(()=>{previews.renderPreviews=oldPreview;globalThis.fetch=oldFetch;if(oldKey===undefined)delete process.env.OPENROUTER_API_KEY;else process.env.OPENROUTER_API_KEY=oldKey;});
 let calls=0;globalThis.fetch=async(_url,options)=>{calls++;const body=JSON.parse(options.body);assert.equal(options.headers['X-Title'],'Greta');assert.equal(body.model,'google/gemini-3.8-flash');if(calls===1){const payload=JSON.parse(body.messages[1].content);assert.equal(payload.project,undefined);assert.ok(payload.projectShape);assert.match(payload.instruction,/from scratch/);}else assert.ok(body.messages[1].content.some(c=>c.type==='image_url'));
  const reply=calls===1?{project:exampleProject(),summary:'Original fixture'}:{approved:true,score:9,issues:[],summary:'Clear fixture frames',criteria,soundPlan:{mode:'silent',name:'No music'}};return {ok:true,json:async()=>({model:'google/gemini-3.8-flash',choices:[{message:{content:JSON.stringify(reply)}}],usage})};};
 const r=await design({brief:'Make a silent 15-second ad',project:null,assets:[],format:'landscape',mode:'create',scope:{kind:'all'}});assert.equal(r.pipeline,'automatic');assert.equal(calls,2);assert.equal(r.usage.total_tokens,200);assert.equal(r.soundPlan.mode,'silent');
});
test('visual reviewer repairs invalid cue timing and counts both attempts',async t=>{
 const oldFetch=globalThis.fetch; t.after(()=>{globalThis.fetch=oldFetch;});let calls=0;
 globalThis.fetch=async(_url,options)=>{calls++;if(calls===2)assert.match(JSON.parse(options.body).messages.at(-1).content,/timeline/);const score=structuredClone(sound);if(calls===1)score.notes.at(-1).frame=440;return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({approved:true,score:9,summary:'Good',issues:[],criteria,soundPlan:score})}}],usage})};};
 const r=await reviewDesign({brief:'An ad',project:exampleProject(),assets:[],images:[]});assert.equal(r.attempts,2);assert.equal(r.usage.total_tokens,200);assert.equal(r.soundPlan.notes.at(-1).frame,390);
});
test('scores produce distinct bounded PCM audio, reject invalid media and retain silence',()=>{
 const a=synthesizeScore(sound,450),other=structuredClone(sound);other.notes[1].midi=65;other.seed=93;const b=synthesizeScore(other,450);assert.equal(a.buffer.toString('ascii',0,4),'RIFF');assert.equal(a.buffer.readUInt32LE(24),48000);assert.equal(a.buffer.length,44+15*48000*2);assert.notDeepEqual(a.buffer,b.buffer);assert.ok(a.peak>0&&a.peak<=.62);
 let peak=0;for(let i=44;i<a.buffer.length;i+=2)peak=Math.max(peak,Math.abs(a.buffer.readInt16LE(i)));assert.ok(peak<32767);assert.equal(a.buffer.readInt16LE(a.buffer.length-2),0);
 assert.throws(()=>validateSoundPlan({...sound,notes:[{...sound.notes[0],frame:449},...sound.notes.slice(1)]},450),/timeline/);assert.throws(()=>validateSoundPlan({...sound,mode:'asset',assetId:'other-user'},450,[]),/supplied/);assert.equal(validateSoundPlan({mode:'silent',name:'Silence'},450).mode,'silent');
});
test('automatic API saves a recoverable revision, private composed audio and an ordinary quota-reserved export',async t=>{
 const express=require('../Questera-Backend/node_modules/express'),jwt=require('../Questera-Backend/node_modules/jsonwebtoken'),{FileStore}=require('../Questera-Backend/motion/store.cjs'),{FileBlobs}=require('../Questera-Backend/motion/blobs.cjs'),{createMotionRouter}=require('../Questera-Backend/motion/router.cjs'),{wallet}=require('../Questera-Backend/motion/worker.cjs');
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'velos-auto-api-')),store=new FileStore(path.join(root,'records')),blobs=new FileBlobs(path.join(root,'blobs')),secret='automatic-api-test-secret'.repeat(3),oldKey=process.env.OPENROUTER_API_KEY;process.env.OPENROUTER_API_KEY='mock-key';let generateCalls=0;
 const app=express();app.use(express.json());const service=createMotionRouter({root,store,blobs,secret,worker:false,local:true,baseUrl:'http://localhost/api/motion',designer:async a=>{generateCalls++;assert.equal(a.pipeline,'automatic');return {...result(),pipeline:'automatic',automation:{passes:[{approved:true,score:9}],generatedLayout:true},soundPlan:sound};}});app.use('/api/motion',service.router);const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{await new Promise(r=>server.close(r));await fs.rm(root,{recursive:true,force:true});if(oldKey===undefined)delete process.env.OPENROUTER_API_KEY;else process.env.OPENROUTER_API_KEY=oldKey;});const base=`http://127.0.0.1:${server.address().port}/api/motion`;
 const call=async(route,method='GET',body,user='alice')=>{const res=await fetch(base+route,{method,headers:{Authorization:`Bearer ${jwt.sign({userId:user},secret)}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:res.status,data:await res.json()};};
 const created=(await call('/projects','POST',{})).data,designed=await call(`/projects/${created.id}/design`,'POST',{brief:'Create my ad automatically',mode:'create',version:created.version});assert.equal(designed.status,200);const r=designed.data;assert.equal(r.applied,true);assert.equal(r.proposal,undefined);assert.equal(r.project.audio.length,1);assert.equal(r.job.status,'queued');assert.equal(r.job.revision,r.version);assert.equal(r.generatedAudio.mode,'generated');assert.equal(r.history[0].version,created.version);assert.deepEqual((await call(`/projects/${created.id}/revisions/${created.version}`)).data.project,created.project);
 const audio=(await call('/assets')).data.assets[0];assert.equal(audio.generated,true);assert.equal(audio.userId,'alice');assert.equal((await call('/assets','GET',null,'bob')).data.assets.length,0);const w=await wallet(store,'alice');assert.equal(w.designs,1);assert.equal(Object.values(w.reservations)[0].seconds,15);
 await store.mutate('usage',w.id,'alice',v=>({...v,limit:15}));const next=await call(`/projects/${created.id}/design`,'POST',{brief:'Another original ad',mode:'create',version:r.version});assert.equal(next.status,200);assert.equal(next.data.applied,true);assert.match(next.data.exportWarning,/allowance/);assert.equal(next.data.job,undefined);
 const latest=next.data;await store.mutate('usage',w.id,'alice',v=>({...v,designs:30}));const blocked=await call(`/projects/${created.id}/design`,'POST',{brief:'One more',mode:'create',version:latest.version});assert.equal(blocked.status,429);assert.equal(generateCalls,2);assert.equal((await call(`/projects/${created.id}`)).data.version,latest.version);
});

test('automatic flow rejects optimistic approval below the requested quality target',async()=>{let calls=0;await assert.rejects(()=>automaticDesign({brief:'An ad',assets:[],format:'square'},{generate:async()=>{calls++;return result();},preview:async()=>[],review:async()=>({approved:true,score:8,issues:[],summary:'Readable, but slide-like',soundPlan:sound,usage,attempts:1})}),e=>e.status===422&&/9\/10/.test(e.message));assert.equal(calls,2);});

test('a high headline score cannot hide weak mobile readability',async t=>{const oldFetch=globalThis.fetch;t.after(()=>{globalThis.fetch=oldFetch;});globalThis.fetch=async()=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({approved:true,score:10,summary:'Clean but tiny text',issues:[],criteria:{...criteria,readability:4},soundPlan:sound})}}],usage})});const r=await reviewDesign({brief:'An ad',project:exampleProject(),assets:[],images:[]});assert.equal(r.approved,false);assert.ok(r.score<9);assert.match(r.issues.join(' '),/readability/);});

test('preview sampling includes each shot opening, action and exact last frame',()=>{const {previewSamples}=require('../Questera-Backend/motion/previews.cjs');const p=exampleProject();p.scenes[0].duration=30;p.scenes[1].duration=60;p.scenes[2].duration=120;const samples=previewSamples(p);assert.equal(samples.length,12);assert.deepEqual(samples.filter(s=>s.sample==='last-frame').map(s=>s.frame),[29,89,209]);assert.deepEqual(samples.filter(s=>s.sample==='opening').map(s=>s.frame),[8,38,98]);assert.equal(new Set(samples.map(s=>s.frame)).size,12);});
