const {motionModel,providerHeaders,generationOptions,APP_TITLE}=require('./provider.cjs');
// AI chooses the story and assets. Trusted recipes compose editable native layers.
async function plannedDesign({brief,assets,format,direction='auto'}){
 const {CreativePlanSchema,composePlan,DIRECTIONS,LAYOUTS}=await import('../../motion/creative-plan.mjs');
 if(direction!=='auto'&&!DIRECTIONS.includes(direction))throw Object.assign(new Error('Choose a supported creative direction.'),{status:400});
 const model=motionModel(),started=Date.now();
 const requested=brief.match(/\b(\d{1,2}(?:\.\d)?)[ -]?second\b/i);const seconds=requested?Number(requested[1]):15;
 const system=`You are a motion-ad creative director. Write a concise story plan, not layer coordinates or code. The app composes editable art-directed layouts from your plan. Make the message specific to the supplied brief. Strong immediate hook, visual explanation or demonstration, payoff, clear closing invitation. Avoid generic filler, duplicated headlines, unsupported features, fake interfaces, invented URLs, prices, testimonials, or performance claims. Do not promise in seconds, in minutes, or in real time or instantly unless that precise turnaround claim is supplied. Use only supplied image asset IDs. Do not pick a screenshot as a logo. For Velos Motion Studio the supported capabilities are AI design, editable text/shapes/scenes, selected-scene or layer refinement, layer locks, uploaded music, timed SRT captions, portrait/landscape/square, and MP4 export. No automatic publishing, voice synthesis, real-time collaboration or 3D claims. Use real product screens in editor/refine layouts only if supplied. Graphical workflow cards are conceptual diagrams, not fake app screenshots. End with layout close. 4–7 shots is usually suitable for 10–20 seconds; honor an explicitly supplied count. Choose varied layouts and purposeful pacing, not repeated slides. The shots have weight .5–8; timing is allocated to the exact duration with at least 84 frames for the close, including two fully readable seconds after its entrance, capped at 108 frames so the close does not dominate the ad. Use no more than 3 punchy words/short phrases in words. The kinetic layout uses these words as type blocks; collage uses them as card labels; ribbon repeats the first word as a graphic. The closing headline/CTA must be at most 32 characters. Other headlines at most 80 characters, labels 40, details 100, brand 28. Omit details when they add no value. Use newline line breaks thoughtfully. Label text must be meaningful customer-facing copy, never recipe names or implementation terms. Choose one coherent palette with at least 7:1 paper/ink contrast. selected is ZERO-BASED: 0 means card 01, 1 means card 02, 2 means card 03. Honor an explicit selected card in the brief. focus left/center/right tells the editor camera which part of the actual supplied screen to show. Return ONLY JSON {plan:{version:1,title,brand,descriptor,direction,seconds,palette:{paper,ink,accent,pop},logoAssetId:null or supplied ID,shots:[{layout,name,weight,headline,label,detail,words:[],assetId:null or supplied ID,afterAssetId:null or supplied ID,selected:1,focus:"left/center/right"}]},summary:"one sentence about the story"}. No extra fields. direction is one of ${DIRECTIONS.join(', ')}. Layout catalog: ${JSON.stringify(LAYOUTS)}. The direction describes the overall character; actual shot layouts must express it. Choose at least three different layouts unless a specific brief requires repetition. Don't copy the catalog's descriptive text into the ad.`;
 const messages=[{role:'system',content:system},{role:'user',content:JSON.stringify({brief,format,direction,seconds,assets:assets.filter(a=>a.kind==='image').map(({id,name,width,height})=>({id,name,width,height})),instruction:direction==='auto'?'Choose the creative direction that best tells this story.':`Use the ${direction} direction.`,example:{version:1,title:'An idea in motion',brand:'Velos',descriptor:'MOTION STUDIO',direction:'editorial',seconds:15,palette:{paper:'#f0ece3',ink:'#16151a',accent:'#7253ed',pop:'#d8ff78'},logoAssetId:null,shots:[{layout:'poster',name:'Opening',weight:1,headline:'Ideas\nmove\nhere.',label:'MAKE SOMETHING MOVE',detail:'',words:[],assetId:null,afterAssetId:null,selected:1},{layout:'workflow',name:'The journey',weight:2,headline:'From a brief\nto a moving story.',label:'YOUR NEXT IDEA',detail:'DESCRIBE / REFINE / EXPORT',words:[],assetId:null,afterAssetId:null,selected:1},{layout:'kinetic',name:'Make it yours',weight:1,headline:'Make it yours.',label:'YOUR WORDS. YOUR STORY.',detail:'',words:['WRITE','MOVE','CREATE'],assetId:null,afterAssetId:null,selected:1},{layout:'close',name:'Invitation',weight:1,headline:'Try Motion Studio',label:'CREATE / REFINE / EXPORT',detail:'Your ideas deserve motion.',words:[],assetId:null,afterAssetId:null,selected:1}]}})}];
 const totals={prompt_tokens:0,completion_tokens:0,total_tokens:0};let cost=0,hasCost=false,failure;
 for(let attempt=0;attempt<2;attempt++){
  const response=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',signal:AbortSignal.timeout(90000),headers:providerHeaders(),body:JSON.stringify({model,messages,...generationOptions(model,4500),response_format:{type:'json_object'}})});
  if(!response.ok)throw Object.assign(new Error(`Design provider could not complete the story (${response.status}). Your project has been preserved.`),{status:502});
  const data=await response.json();for(const key of Object.keys(totals))totals[key]+=Number(data.usage?.[key]||0);if(Number.isFinite(data.usage?.cost)){cost+=data.usage.cost;hasCost=true;}const text=data.choices?.[0]?.message?.content||'';
  try{const parsed=JSON.parse(text.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''));const plan=CreativePlanSchema.parse(parsed.plan);if(direction!=='auto')plan.direction=direction;const composed=composePlan(plan,{format,assets,brief,seconds});return {project:composed.project,plan:composed.plan,summary:String(parsed.summary||'A new visual story, composed with art-directed motion layouts.').slice(0,400),usage:{...totals,cost:hasCost?cost:undefined,accounting:'all-provider-attempts'},model:data.model||model,requestedModel:model,appTitle:APP_TITLE,attempts:attempt+1,latencyMs:Date.now()-started,pipeline:'guided',direction:composed.plan.direction};}
  catch(e){failure=e;messages.push({role:'assistant',content:text},{role:'user',content:`Correct the story plan. Validation: ${e.message.slice(0,2000)}. Keep the brief and return full JSON with plan and summary.`});}
 }
 const detail=(failure?.message||'Invalid story').slice(0,350);throw Object.assign(new Error(`The story did not pass validation after two attempts. Your project has been preserved. ${detail}`),{status:422});
}
module.exports={plannedDesign};
