const {motionModel,APP_TITLE}=require('./provider.cjs');
const express=require('express');const jwt=require('jsonwebtoken');const crypto=require('node:crypto');const path=require('node:path');const fs=require('node:fs/promises');const os=require('node:os');const {execFile}=require('node:child_process');const {promisify}=require('node:util');
const {FileStore,MongoStore,problem}=require('./store.cjs');const {FileBlobs,S3Blobs}=require('./blobs.cjs');const {makeWorker,reserve,settle,wallet}=require('./worker.cjs');const {design}=require('./design.cjs');
const {mediaKey}=require('./security.cjs');
const schemas=()=>import('../../motion/schema.mjs');
const uid=()=>crypto.randomUUID();
function createMotionRouter(options={}){
 const root=path.resolve(options.root||process.env.MOTION_DATA_DIR||path.join(__dirname,'../../.motion-data'));const store=options.store||new MongoStore();const blobs=options.blobs||(process.env.MOTION_STORAGE==='local'?new FileBlobs(path.join(root,'blobs')):new S3Blobs());const secret=options.secret||process.env.JWT_SECRET;
 if(!secret)throw new Error('Motion API requires a signing secret.');
 const base=options.baseUrl||process.env.MOTION_PUBLIC_API_URL;if(!base)throw new Error('Motion API requires MOTION_PUBLIC_API_URL (absolute /api/motion URL).');
 const mediaSecret=mediaKey(secret);const router=express.Router();const ticket=(kind,id,userId)=>jwt.sign({kind,id,userId},mediaSecret,{expiresIn:'4h',audience:'motion-media',algorithm:'HS256'});
 const urlsFor=assets=>Object.fromEntries(assets.map(a=>[a.id,`${base}/assets/${a.id}/file?ticket=${ticket('asset',a.id,a.userId)}`]));
 try{const url=new URL(base);if(!['http:','https:'].includes(url.protocol)||url.search||url.hash)throw new Error();}catch{throw new Error('MOTION_PUBLIC_API_URL must be an absolute HTTP(S) URL without a query.');}
 const worker=(options.worker===false||(!options.local&&process.env.MOTION_INLINE_WORKER!=='true'))?{tick:()=>{},stop:()=>{}}:makeWorker({store,blobs,root,urlsFor});
 function mediaAuth(req,res,next){try{const token=req.query.ticket;const decoded=jwt.verify(token,mediaSecret,{audience:'motion-media',algorithms:['HS256']});if(decoded.id!==req.params.id||decoded.kind!==req.mediaKind)throw new Error();req.user={userId:decoded.userId};next();}catch{res.status(401).json({error:'This media link expired or is invalid. Reload the project.'});}}
 router.get('/assets/:id/file',(req,res,next)=>{req.mediaKind='asset';mediaAuth(req,res,next);},async(req,res)=>{const asset=await store.get('asset',req.params.id,req.user.userId);if(!asset)throw problem('Asset not found.',404);res.type(asset.mimeType).set('Cache-Control','private, max-age=300').set('X-Content-Type-Options','nosniff');await blobs.send(asset.id,res,req);});
 router.get('/exports/:id/file',(req,res,next)=>{req.mediaKind='job';mediaAuth(req,res,next);},async(req,res)=>{const job=await store.get('job',req.params.id,req.user.userId);if(!job||job.status!=='completed')throw problem('Export is not ready.',404);const poster=req.query.poster==='1';res.type(poster?'image/png':'video/mp4');if(!poster)res.set('Content-Disposition',`${req.query.inline==='1'?'inline':'attachment'}; filename="velos-${job.id.slice(0,8)}.mp4"`);res.set('X-Content-Type-Options','nosniff');await blobs.send(`${job.id}.${poster?'png':'mp4'}`,res,req);});
 router.use((req,res,next)=>{try{const auth=req.headers.authorization;if(!auth?.startsWith('Bearer '))throw new Error();const decoded=jwt.verify(auth.slice(7),secret,{algorithms:['HS256']});if(typeof decoded.userId!=='string'||!decoded.userId)throw new Error();req.user={userId:decoded.userId};next();}catch{res.status(401).json({error:'Please sign in to use Motion Studio.'});}});
 const present=(record)=>({...record,history:record.history?.map(({version,savedAt,title})=>({version,savedAt,title}))});
 const save=async(id,userId,project,version,extra={})=>store.mutate('project',id,userId,r=>({...r,...extra,project,history:[{version:r.version,project:r.project,savedAt:r.updatedAt,title:r.project.title},...(r.history||[])].slice(0,25)}),version);
 const jobSeconds=j=>j.kind==='prompt-video'?j.snapshot.duration:j.snapshot.scenes.reduce((n,s)=>n+s.duration,0)/30;
 const jobView=j=>({id:j.id,kind:j.kind||'native',projectId:j.projectId,revision:j.revision,title:j.title,status:j.status,stage:j.stage,progress:j.progress,error:j.error?.replace(/https?:\/\/[^\s]+/g,'[private media]'),createdAt:j.createdAt,updatedAt:j.updatedAt,duration:jobSeconds(j),...(j.kind==='prompt-video'?{prompt:j.snapshot.brief,format:j.snapshot.format,music:j.snapshot.music,review:j.generated?.assessment,designUsage:j.generated?.usage||j.designUsage,canRetry:!!j.generated}:{}),...(j.status==='completed'?{url:`${base}/exports/${j.id}/file?ticket=${ticket('job',j.id,j.userId)}`,poster:`${base}/exports/${j.id}/file?poster=1&ticket=${ticket('job',j.id,j.userId)}`}:{})});
 let pythonAvailability,pythonCheckedAt=0;const pythonStatus=async()=>{if(!pythonAvailability||Date.now()-pythonCheckedAt>60000){pythonAvailability=await (options.promptStatus||require('./python-renderer.cjs').pythonStatus)();pythonCheckedAt=Date.now();}return pythonAvailability;};
 router.get('/status',async(req,res)=>{const w=await wallet(store,req.user.userId);const used=Object.values(w.reservations||{}).filter(r=>r.state!=='released').reduce((n,r)=>n+r.seconds,0);res.json({local:!!options.local,aiConfigured:!!process.env.OPENROUTER_API_KEY,speechConfigured:!!process.env.OPENAI_API_KEY,remainingSeconds:Math.max(0,w.limit-used),dailyLimit:w.limit,designs:w.designs,dailyDesignLimit:designLimit,defaultPipeline:'automatic',model:motionModel(),appTitle:APP_TITLE,promptVideo:await pythonStatus()});});
 router.get('/projects',async(req,res)=>{const records=await store.list('project',req.user.userId);res.json({projects:records.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(present)});});
 router.post('/projects',async(req,res)=>{const {ProjectSchema,exampleProject}=await schemas();const project=req.body.project?ProjectSchema.parse(req.body.project):exampleProject(req.body.style,req.body.format||'landscape');const assets=await store.list('asset',req.user.userId);const {validateAssets}=await schemas();const issues=validateAssets(project,assets);if(issues.length)throw problem(issues.join(' '));const count=(await store.list('project',req.user.userId)).filter(p=>!p.archived).length;if(count>=100)throw problem('Beta project limit reached.',429);res.status(201).json(present(await store.create('project',{id:uid(),userId:req.user.userId,project,isStarter:!req.body.project,history:[],chats:[],archived:false,createdAt:new Date().toISOString()})));});
 router.get('/projects/:id',async(req,res)=>{const r=await store.get('project',req.params.id,req.user.userId);if(!r)throw problem('Project not found.',404);res.json(present(r));});
 router.put('/projects/:id',async(req,res)=>{const {ProjectSchema,validateAssets}=await schemas();if(!Number.isInteger(req.body.version))throw problem('A project revision is required.');const project=ProjectSchema.parse(req.body.project);const issues=validateAssets(project,await store.list('asset',req.user.userId));if(issues.length)throw problem(issues.join(' '));res.json(present(await save(req.params.id,req.user.userId,project,req.body.version)));});
 router.get('/projects/:id/revisions/:version',async(req,res)=>{const r=await store.get('project',req.params.id,req.user.userId);if(!r)throw problem('Project not found.',404);const h=r.history.find(v=>v.version===Number(req.params.version));if(!h)throw problem('Revision not found.',404);res.json({project:h.project});});
 router.post('/projects/:id/archive',async(req,res)=>{if(!Number.isInteger(req.body.version))throw problem('A project revision is required.');res.json(present(await store.mutate('project',req.params.id,req.user.userId,r=>({...r,archived:req.body.archived!==false}),req.body.version)));});
 router.get('/assets',async(req,res)=>{const assets=await store.list('asset',req.user.userId);const urls=urlsFor(assets);res.json({assets:assets.map(a=>({...a,url:urls[a.id]}))});});
 router.post('/assets',async(req,res)=>{const {name,mimeType,data}=req.body;if(typeof data!=='string'||data.length>58*1024*1024||!/^[A-Za-z0-9+/]+={0,2}$/.test(data))throw problem('Upload a valid file under 40 MB.');const buffer=Buffer.from(data,'base64');if(buffer.length>40*1024*1024)throw problem('Files are limited to 40 MB.');
 const allowed={'image/png':'image','image/jpeg':'image','image/webp':'image','video/mp4':'video','audio/mpeg':'audio','audio/wav':'audio','audio/x-wav':'audio','audio/ogg':'audio','audio/mp4':'audio'};const kind=allowed[mimeType];if(!kind)throw problem('Use PNG, JPG, WebP, MP4, MP3, WAV, OGG, or M4A.');
 const magic=buffer.subarray(0,12);const valid=(mimeType==='image/png'?magic.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):mimeType==='image/jpeg'?magic[0]===255&&magic[1]===216:mimeType==='image/webp'?magic.toString('ascii',0,4)==='RIFF'&&magic.toString('ascii',8,12)==='WEBP':kind==='video'||mimeType==='audio/mp4'?magic.toString('ascii',4,8)==='ftyp':mimeType.includes('wav')?magic.toString('ascii',0,4)==='RIFF'&&magic.toString('ascii',8,12)==='WAVE':mimeType==='audio/ogg'?magic.toString('ascii',0,4)==='OggS':magic.toString('ascii',0,3)==='ID3'||(magic[0]===255&&(magic[1]&224)===224));if(!valid)throw problem('File content does not match its media type.');
 const asset={id:uid(),userId:req.user.userId,name:String(name||'Untitled asset').slice(0,120),mimeType,kind,size:buffer.length,createdAt:new Date().toISOString()};
 if((await store.list('asset',req.user.userId)).length>=200)throw problem('Beta asset limit reached.',429);
 {const temp=path.join(os.tmpdir(),`velos-media-${uid()}`);try{await fs.writeFile(temp,buffer);const {stdout}=await promisify(execFile)(process.env.MOTION_FFPROBE||'ffprobe',['-v','error','-show_entries','format=duration:stream=codec_type,width,height','-of','json',temp],{timeout:15000,maxBuffer:100000});const meta=JSON.parse(stdout);asset.duration=kind==='image'?undefined:Number(meta.format?.duration);if(kind!=='image'&&(!Number.isFinite(asset.duration)||asset.duration<=0||asset.duration>600))throw problem('Media must be between 0 and 600 seconds.');const v=meta.streams?.find(s=>s.codec_type==='video');if((kind==='video'||kind==='image')&&!v)throw problem('MP4 must contain a video track.');if(v){asset.width=v.width;asset.height=v.height;if(!asset.width||!asset.height||asset.width*asset.height>40000000)throw problem('Media dimensions must be valid and under 40 megapixels.');}if(kind==='audio'&&!meta.streams?.some(s=>s.codec_type==='audio'))throw problem('Audio track is missing.');}catch(e){if(e.status)throw e;throw problem('Could not read this media. Check the file and ffprobe installation.');}finally{await fs.rm(temp,{force:true});}}
 await blobs.put(asset.id,buffer,mimeType);const saved=await store.create('asset',asset);res.status(201).json({...saved,url:urlsFor([saved])[saved.id]});});
 router.post('/assets/:id/transcribe',async(req,res)=>{const asset=await store.get('asset',req.params.id,req.user.userId);if(!asset||asset.kind!=='audio')throw problem('Audio asset not found.',404);if(asset.size>25*1024*1024)throw problem('Automatic captions require audio under 25 MB.');if(!process.env.OPENAI_API_KEY)throw problem('Automatic captions are currently unavailable. Import a timed SRT file instead.',503);const response=await fetch(urlsFor([asset])[asset.id],{signal:AbortSignal.timeout(20000)});if(!response.ok)throw problem('Could not load this audio.',502);const w=await wallet(store,req.user.userId);await store.mutate('usage',w.id,req.user.userId,v=>{if(v.designs>=designLimit)throw problem('Daily AI allowance reached.',429);return {...v,designs:v.designs+1};});const {transcribe}=require('./speech.cjs');res.json(await transcribe(Buffer.from(await response.arrayBuffer()),asset.mimeType));});
 const designing=new Set();const designer=options.designer||design;const designLimit=options.local?Number(process.env.MOTION_LOCAL_AI_LIMIT||30):30;if(!Number.isInteger(designLimit)||designLimit<1||designLimit>100)throw new Error('MOTION_LOCAL_AI_LIMIT must be an integer from 1 to 100.');
 router.get('/videos',async(req,res)=>res.json({videos:(await store.list('job',req.user.userId)).filter(j=>j.kind==='prompt-video').sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(jobView)}));
 router.get('/videos/:id',async(req,res)=>{const job=await store.get('job',req.params.id,req.user.userId);if(!job||job.kind!=='prompt-video')throw problem('Video not found.',404);res.json(jobView(job));});
 router.post('/videos',async(req,res)=>{
  const {brief,format='landscape',duration=15,music='generated',requestId}=req.body,userId=req.user.userId;
  if(typeof brief!=='string'||!brief.trim()||brief.length>4000)throw problem('Describe your video in up to 4,000 characters.');
  if(!['landscape','portrait','square'].includes(format)||!Number.isInteger(duration)||duration<5||duration>30||!['generated','silent'].includes(music))throw problem('Choose a format, a duration from 5 to 30 seconds, and a soundtrack setting.');
  if(typeof requestId!=='string'||!/^[\w-]{8,100}$/.test(requestId))throw problem('A video request ID is required.');
  const snapshot={engine:'python',brief:brief.trim(),format,duration,music};
  const id=crypto.createHash('sha256').update(`${userId}:prompt-video:${requestId}`).digest('hex');const existing=await store.get('job',id,userId);
  if(existing){if(existing.kind!=='prompt-video'||JSON.stringify(existing.snapshot)!==JSON.stringify(snapshot))throw problem('This request ID belongs to a different video.',409);if(existing.status==='admitting')throw problem('This video request is being queued. Try again shortly.',409);res.status(200).json(jobView(existing));return;}
  if(designing.has(userId)||(await store.list('job',userId)).some(j=>j.kind==='prompt-video'&&['queued','processing'].includes(j.status)))throw problem('A video design is already in progress.',409);
  if(!process.env.OPENROUTER_API_KEY)throw problem('AI video design is not configured.',503);
  if(!(await pythonStatus()).available)throw problem('Prompt video rendering is unavailable. Build the motion Python worker image.',503);
  const w=await wallet(store,userId);if(w.designs>=designLimit)throw problem('Daily AI design limit reached.',429);
  designing.add(userId);let job;
  try{
   job=await store.create('job',{id,userId,kind:'prompt-video',projectId:null,revision:1,title:brief.trim().slice(0,80),snapshot,walletId:w.id,status:'admitting',stage:'queued',progress:0,createdAt:new Date().toISOString()});
   const walletId=await reserve(store,userId,id,duration);job.walletId=walletId;
   await store.mutate('usage',w.id,userId,v=>{if(v.designs>=designLimit)throw problem('Daily AI design limit reached.',429);return {...v,designs:v.designs+1};});
   job=await store.mutate('job',id,userId,j=>({...j,walletId,aiReserved:true,status:'queued'}));
   res.status(202).json(jobView(job));worker.tick();
  }catch(e){if(job){await settle(store,job,false);await store.mutate('job',id,userId,j=>({...j,status:'failed',error:e.message}));}throw e;}
  finally{designing.delete(userId);}
 });
 router.post('/projects/:id/design',async(req,res)=>{const userId=req.user.userId;if(designing.has(userId))throw problem('A design is already in progress.',409);const {brief,version,mode='edit'}=req.body;if(!['create','edit'].includes(mode))throw problem('Choose create or edit mode.');if(typeof brief!=='string'||!brief.trim()||brief.length>4000||!Number.isInteger(version))throw problem('Use a brief up to 4000 characters and a project revision.');const before=await store.get('project',req.params.id,userId);if(!before)throw problem('Project not found.',404);if(before.version!==version)throw problem('Save or reload your latest changes before designing.',409);
 if(!process.env.OPENROUTER_API_KEY)throw problem('AI design is not configured.',503);const w=await wallet(store,userId);if(w.designs>=designLimit)throw problem('Daily AI design limit reached.',429);designing.add(userId);
 try{await store.mutate('usage',w.id,userId,r=>{if(r.designs>=designLimit)throw problem('Daily AI design limit reached.',429);return {...r,designs:r.designs+1};});if(!process.env.OPENROUTER_API_KEY)throw problem('AI design is not configured.',503);const {editScope}=await import('../../motion/edits.mjs');let scope;try{scope=editScope(before.project,brief,req.body.scope||'auto',req.body.targetId);}catch(e){throw problem(e.message);}
 const assets=await store.list('asset',userId);let result=await designer({brief,scope,project:mode==='create'?null:before.project,assets,format:before.project.format,mode,pipeline:req.body.pipeline||'automatic',direction:req.body.direction||'auto',renderContext:{urls:urlsFor(assets)}});
 if(result.soundPlan){const {attachSound}=require('./audio-assets.cjs');result=await attachSound({result,assets,store,blobs,userId});}
 const chats=[...(before.chats||[]),{role:'user',text:brief},{role:'assistant',text:result.summary,model:result.model}].slice(-40),extra={chats,...(result.plan?{designPlan:result.plan}:{}),designAutomation:result.automation||null,generatedAudio:result.generatedAudio||null,designUsage:{model:result.model,requestedModel:result.requestedModel,appTitle:result.appTitle,attempts:result.attempts,latencyMs:result.latencyMs,tokens:result.usage?.total_tokens,cost:result.usage?.cost,tokenAccounting:result.usage?.accounting,pipeline:result.pipeline,direction:result.direction}};
 const applied=mode==='create'&&result.pipeline==='automatic'&&req.body.autoApply!==false;
 const updated=applied?await save(before.id,userId,result.project,version,extra):await store.mutate('project',before.id,userId,r=>({...r,...extra}),version);
 let job,exportWarning;if(applied&&req.body.autoExport!==false){try{job=jobView(await queueExport(updated,`automatic-${updated.id}-${updated.version}`));}catch(e){exportWarning=e.status===429?'Design is saved. Daily render allowance reached; export when allowance is available.':'Design is saved, but export could not be queued. Use Export MP4 to retry.';}}
 res.json({...present(updated),applied,...(job?{job}:{}),...(exportWarning?{exportWarning}:{}),...(applied?{}:{proposal:{project:result.project,summary:result.summary,...(result.plan?{plan:result.plan}:{})}})});}finally{designing.delete(userId);}});
 async function queueExport(p,requestId){
 const {ProjectSchema,validateAssets,durationOf}=await schemas();ProjectSchema.parse(p.project);const issues=validateAssets(p.project,await store.list('asset',p.userId));if(issues.length)throw problem(issues.join(' '));
if(typeof requestId!=='string'||!/^[\w-]{8,100}$/.test(requestId))throw problem('An export request ID is required.');const id=crypto.createHash('sha256').update(`${p.userId}:${requestId}`).digest('hex');const existing=await store.get('job',id,p.userId);if(existing){if(existing.projectId!==p.id||existing.revision!==p.version)throw problem('This export request ID was used for another revision.',409);return existing;}
 const walletId=await reserve(store,p.userId,id,durationOf(p.project)/30);const job={id,userId:p.userId,projectId:p.id,revision:p.version,title:p.project.title,snapshot:p.project,status:'queued',progress:0,createdAt:new Date().toISOString(),walletId};
 try{const result=await store.create('job',job);worker.tick();return result;}catch(e){if(e.status===409){return store.get('job',id,p.userId);}await settle(store,job,false);throw e;}
 }
 router.get('/exports',async(req,res)=>res.json({jobs:(await store.list('job',req.user.userId)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(jobView)}));
 router.post('/projects/:id/export',async(req,res)=>{const p=await store.get('project',req.params.id,req.user.userId);if(!p)throw problem('Project not found.',404);if(p.version!==req.body.version)throw problem('Save the latest project before exporting.',409);const {ProjectSchema,validateAssets,durationOf}=await schemas();ProjectSchema.parse(p.project);const issues=validateAssets(p.project,await store.list('asset',req.user.userId));if(issues.length)throw problem(issues.join(' '));
 const result=await queueExport(p,req.body.requestId);res.status(202).json(jobView(result));});
 router.post('/exports/:id/retry',async(req,res)=>{const job=await store.get('job',req.params.id,req.user.userId);if(!job)throw problem('Export not found.',404);if(!['failed','cancelled'].includes(job.status)||(job.attempts||0)>=3)throw problem('Create a new export after three attempts or wait for the current export.',409);if(job.kind==='prompt-video'&&!job.generated)throw problem('Revise your prompt and create a new video. This design has no approved scene to re-render.',409);const walletId=await reserve(store,job.userId,job.id,jobSeconds(job));const queued=await store.mutate('job',job.id,job.userId,j=>({...j,walletId,status:'queued',progress:0,error:null}),job.version);res.status(202).json(jobView(queued));worker.tick();});
 router.post('/exports/:id/cancel',async(req,res)=>{const job=await store.mutate('job',req.params.id,req.user.userId,j=>['queued','processing'].includes(j.status)?{...j,status:'cancelled',error:null}:null);if(job)await settle(store,job,false);res.json(job?jobView(job):{status:'unchanged'});});
 router.use((e,req,res,next)=>{if(req.aborted||res.destroyed)return;if(res.headersSent)return next(e);const status=e.name==='ZodError'?400:e.status||500;console.error('[MOTION API]',status,e.message.slice(0,150));res.status(status).type('application/json').json({error:status===500?'Motion Studio could not complete this request. Try again.':e.name==='ZodError'?'Project validation failed. Check layer sizes and timing.':e.message});});
 return {router,store,blobs,worker,urlsFor};
}
module.exports={createMotionRouter};
