const { OpenRouterProvider } = require('../agent/LLMProvider');
const { PlatformDefaults } = require('../agent/PlatformDefaults');
const AutopilotTask = require('../models/autopilotTask');
const ScheduledPost = require('../models/scheduledPost');

// Which platforms expose post analytics to us. LinkedIn personal profiles do
// not (needs r_member_social, which is restricted), so its agent must reason
// from what was posted, not how it performed.
const METRICS_AVAILABLE = { instagram: true, twitter: true, linkedin: false };

// Phrases that promise material the pipeline cannot make. Everything the
// autopilot posts is GENERATED - from the brand profile and any uploaded
// reference images. It has no screen recorder, no camera and no product access.
const UNPRODUCIBLE = [
  [/\b(short|quick|brief) screen[- ]?recordings?\b/gi, 'short generated clips'],
  [/\bscreen[- ]?recordings?\b/gi, 'generated clips'],
  [/\bscreen ?casts?\b/gi, 'generated clips'],
  [/\bscreenshots?\b/gi, 'generated visuals'],
  [/\bUI (tours?|walkthroughs?|demos?)\b/gi, 'visual explainers'],
  [/\b(real|actual|live|authentic) (customer|user|team|office|product) (photos?|videos?|footage)\b/gi, 'illustrative visuals'],
  [/\b(real|actual|live|authentic) (photos?|footage|videos?)\b/gi, 'illustrative visuals'],
  [/\bbehind[- ]the[- ]scenes (photos?|footage|videos?)\b/gi, 'illustrative visuals'],
  [/\bcustomer (photos?|testimonial videos?)\b/gi, 'illustrative visuals'],
];

// Per-platform guard rails for what the planner may propose.
const PLATFORM_RULES = {
  instagram: {
    formats: ['image', 'multi_image', 'video'],
    maxTotalPerDay: 3,
    guidance: 'Instagram is visual-first. Every task should produce a strong image or video. Square or 4:5.',
  },
  linkedin: {
    formats: ['text', 'image', 'multi_image', 'video'],
    maxTotalPerDay: 2,
    guidance: 'LinkedIn rewards substance over frequency. Two posts a day across ALL tasks is the ceiling; one is healthier. Prefer text and single landscape images.',
  },
  twitter: {
    formats: ['text', 'thread', 'image', 'multi_image', 'video'],
    maxTotalPerDay: 4,
    guidance: 'X rewards frequency and sharpness. Short text posts and threads carry the account; images support. 280 characters per post. IMPORTANT: X bills a post containing a URL at 13x the price of a plain post - put linkUrl on at most ONE task (the one where a click matters, e.g. pricing or signup) and leave the others without a link.',
  },
};

const GENERATED_ONLY = `- Images and carousels GENERATED by an image model: illustrations, typographic graphics, diagrams, abstract product-themed scenes, quote cards, stat cards.
- Short videos GENERATED by a video model from a text prompt (and any uploaded reference images).
- It has NO screen recorder, NO camera, NO access to the product itself. Never promise screenshots, screen recordings, UI tours, real photos, real customers or real footage. Keep every task a GENERAL post beat - the exact visual is decided at run time.`;
const WITH_STUDIO = `- Product images made from the company's OWN WEBSITE: a real screen of the site in a browser window under the post's headline, and carousels designed in the brand's colours and fonts (a cover, one slide per point, a closing slide).
- Product videos (20-45 seconds, with music) made from the company's real website screens: a feature, how it works, or what is new. Plan ONE product video task, about twice a week.
- It has NO camera: never promise photos or footage of people, customers, offices or events. Keep every task a GENERAL post beat - the exact screen and story are decided at run time.`;
const REVIEW_GENERATED_ONLY = 'The pipeline can only GENERATE material (text, generated images/carousels, generated video). Never suggest screenshots, screen recordings, real photos or real footage.';
const REVIEW_WITH_STUDIO = "The pipeline makes text, images and carousels from the company's own website screens, and product videos from those screens. Never suggest photos or footage of people.";

const SYSTEM_PROMPT = `You are the {PLATFORM_AGENT} - the specialist who runs ONE company's presence on {PLATFORM_NAME}.

You will be given the company's brand profile (built from its own website), the platform's constraints, and - when available - how the account's past posts performed.

Design 4-5 RECURRING TASKS. A task is a standing job that runs on a schedule and produces one post each time - not a single post. Think of them as the columns of a magazine: each has its own beat, its own format and its own rhythm.

WHAT THE PIPELINE CAN ACTUALLY MAKE - design only within this:
- Text posts and threads written from the brand profile.
- Images and carousels GENERATED by an image model: illustrations, typographic graphics, diagrams, abstract product-themed scenes, quote cards, stat cards.
- Short videos GENERATED by a video model from a text prompt (and any uploaded reference images).
- It has NO screen recorder, NO camera, NO access to the product itself. Never promise screenshots, screen recordings, UI tours, real photos, real customers or real footage. Keep every task a GENERAL post beat - the exact visual is decided at run time.
- Every post can carry a LINK to a page on the company's website. Give each task the most relevant page (from the list provided, or the homepage) and a short call to action. A task may also have no link if a link would cheapen it.

WHAT MAKES A GOOD SET OF TASKS:
- Each task has a DISTINCT beat. No two tasks should produce interchangeable posts.
- Mix formats. A set that is five image tasks is a worse account than one with text, image and video.
- Mix cadences. The cheap, high-frequency task carries reach; the expensive one runs weekly.
- Ground each task in what the company actually does. Use the proof points.
- If performance data is given, lean into what worked and drop what did not - and say so in "reasoning".
- Video is expensive and slow to produce. At most ONE video task, and never more than a few times a week.
- Respect the platform's total daily ceiling ACROSS ALL TASKS.

RULES:
- Do not invent facts, customers or metrics beyond the brand profile.
- "angle" is the standing instruction for every run of that task - it must be repeatable, not a one-off idea.
- linkUrl must be one of the site pages listed, or the homepage, or "".
- times must have exactly timesPerDay entries, in "HH:MM" 24-hour form.
- daysOfWeek uses 0 for Sunday. Weekdays are [1,2,3,4,5].

Respond with ONLY valid JSON:

{
  "tasks": [
    {
      "name": "short human label, 2-4 words",
      "description": "one sentence on what this task posts and why it earns its place",
      "angle": "the standing instruction every run follows",
      "format": "text|thread|image|multi_image|video",
      "theme": "one word",
      "hookStyle": "one word",
      "goal": "reach|comments|reshares|saves|follows|clicks",
      "linkUrl": "https://... or empty",
      "cta": "3-6 words, e.g. Try it free",
      "timesPerDay": 1,
      "times": ["09:00"],
      "daysOfWeek": [1,2,3,4,5]
    }
  ],
  "reasoning": "1-2 sentences on why this mix suits this company on this platform"
}`;

const REVIEW_PROMPT = `You are the {PLATFORM_AGENT} reviewing the recurring tasks you run for ONE company on {PLATFORM_NAME}.

You get the brand profile, the current task list (with each task's run count and posts made), and the account's post performance where the platform exposes it.

Your job: tell the owner, plainly, what is working, what is not, and what to change. Be specific and numeric where the data allows. When the platform gives no metrics, say so once and reason from the content mix instead - do not treat silence as poor performance.

The pipeline can only GENERATE material (text, generated images/carousels, generated video). Never suggest screenshots, screen recordings, real photos or real footage.

Respond with ONLY valid JSON:
{
  "summary": "2-3 sentences, the state of this account in your voice",
  "insights": ["short, specific observation", "..."],
  "suggestions": [
    {
      "taskId": "id of an existing task, or null for a new one",
      "title": "what to change, 3-8 words",
      "reason": "one sentence why, citing data when there is any",
      "patch": { "schedule": { "timesPerDay": 1, "times": ["09:00"], "daysOfWeek": [1,3,5] }, "format": "image", "enabled": true, "linkUrl": "", "cta": "" }
    }
  ]
}
"patch" contains ONLY the fields that should change. 2-5 suggestions. If nothing should change, return an empty suggestions array and say why in summary.`;

const AGENT_NAMES = { instagram: 'Instagram growth agent', linkedin: 'LinkedIn growth agent', twitter: 'X growth agent' };

/**
 * Turns a brand profile into a set of recurring content tasks.
 *
 * This runs once at setup (and again on demand), not on every post. The daily
 * decision of what to write is made per task at run time; this decides what
 * the account's standing beats are.
 */
class TaskPlanner {
  constructor() {
    this.llm = new OpenRouterProvider({ model: process.env.AUTOPILOT_LLM_MODEL || 'google/gemini-3.7-flash' });
  }

  systemPrompt(template, platform, { studio = false } = {}) {
    const spec = PlatformDefaults.get(platform);
    let out = template
      .replace(/\{PLATFORM_AGENT\}/g, AGENT_NAMES[platform] || 'growth agent')
      .replace(/\{PLATFORM_NAME\}/g, spec.name);
    // With the company's site connected and Studio on, the pipeline shows the real product (functions/PostImages.js,
    // AutopilotService.makeProductVideo) instead of only generating visuals.
    if (studio) out = out.split(GENERATED_ONLY).join(WITH_STUDIO).split(REVIEW_GENERATED_ONLY).join(REVIEW_WITH_STUDIO);
    return out;
  }

  /**
   * What this account's past posts did, from the publish ledger. Grouped by
   * format so the agent can compare beats, plus the top posts by likes.
   */
  async performanceSummary({ userId, autopilotId, platform }) {
    const query = { userId, platform, status: 'published', ...(autopilotId ? { autopilotId } : {}) };
    const posts = await ScheduledPost.find(query).sort({ publishedAt: -1 }).limit(60)
      .select('postType caption engagement publishedAt platformPostUrl');

    const metricsAvailable = METRICS_AVAILABLE[platform] !== false;
    const measured = posts.filter((p) => p.engagement?.lastUpdated);
    const byFormat = {};
    for (const p of measured) {
      const e = p.engagement || {};
      const f = byFormat[p.postType] || (byFormat[p.postType] = { posts: 0, likes: 0, comments: 0, shares: 0, saves: 0, impressions: 0 });
      f.posts += 1; f.likes += e.likes || 0; f.comments += e.comments || 0; f.shares += e.shares || 0; f.saves += e.saves || 0; f.impressions += e.impressions || e.reach || 0;
    }
    const top = [...measured]
      .sort((a, b) => ((b.engagement?.likes || 0) + (b.engagement?.comments || 0)) - ((a.engagement?.likes || 0) + (a.engagement?.comments || 0)))
      .slice(0, 3)
      .map((p) => ({ postType: p.postType, caption: (p.caption || '').slice(0, 140), likes: p.engagement?.likes || 0, comments: p.engagement?.comments || 0, impressions: p.engagement?.impressions || p.engagement?.reach || 0 }));

    return { metricsAvailable, published: posts.length, measured: measured.length, byFormat, top };
  }

  formatPerformance(perf) {
    if (!perf) return 'No performance data.';
    if (!perf.metricsAvailable) {
      return `This platform exposes NO engagement metrics to us for this account. ${perf.published} post(s) published so far. Reason from the content mix, not from performance.`;
    }
    if (perf.measured === 0) return `${perf.published} post(s) published; none have engagement data yet.`;
    const rows = Object.entries(perf.byFormat).map(([f, v]) =>
      `- ${f}: ${v.posts} post(s), avg ${(v.likes / v.posts).toFixed(1)} likes, ${(v.comments / v.posts).toFixed(1)} comments, ${(v.shares / v.posts).toFixed(1)} shares, ${Math.round(v.impressions / v.posts)} impressions`);
    const top = perf.top.map((t, i) => `${i + 1}. [${t.postType}] ${t.likes} likes / ${t.comments} comments / ${t.impressions} impr - "${t.caption}"`);
    return `${perf.measured} of ${perf.published} published posts have metrics.\n\nBy format:\n${rows.join('\n')}\n\nTop posts:\n${top.join('\n')}`;
  }

  buildPrompt(brand, platform, { pages = [], performance = null } = {}) {
    const rules = PLATFORM_RULES[platform] || PLATFORM_RULES.instagram;
    const spec = PlatformDefaults.get(platform);

    return `## Platform
${spec.name}
${rules.guidance}
Allowed formats: ${rules.formats.join(', ')}
Maximum posts per day across ALL tasks combined: ${rules.maxTotalPerDay}
Caption limit: ${spec.caption.maxLength} characters, ${spec.caption.hashtagLimit} hashtags max
Best posting times: ${spec.bestTimes.join(', ')}

## The Company
${brand.companyName || 'Unnamed'}
${brand.oneLiner || ''}

Audience: ${brand.targetAudience || 'not specified'}
Tone: ${brand.tone || 'professional'}
Visual style: ${brand.visualStyle || 'modern'}
Topics: ${(brand.topicsAllowed || []).join(', ') || 'not specified'}

### Proof points (real facts from their site)
${(brand.proofPoints || []).map((p, i) => `${i + 1}. ${p}`).join('\n') || 'None available.'}

### Content angles they could return to
${(brand.contentAngles || []).join(' | ') || 'Not specified.'}

### Site pages a post may link to
${pages.length ? pages.map((p) => `- ${p.url}${p.title ? ` (${p.title})` : ''}`).join('\n') : '- (homepage only)'}

### How past posts performed
${this.formatPerformance(performance)}

Design the 4-5 recurring tasks that would run this account well.`;
  }

  /** Strip promises of material the pipeline cannot produce. */
  sanitize(text, { studio = false } = {}) {
    let out = String(text || '');
    // With Studio, real screens of the site are producible; photos and footage of people still are not.
    for (const [re, rep] of studio ? UNPRODUCIBLE.slice(5) : UNPRODUCIBLE) out = out.replace(re, rep);
    return out;
  }

  /** A link is only kept if it points at the company's own site. */
  sanitizeLink(url, site) {
    if (!url) return '';
    try {
      const u = new URL(String(url));
      if (site) {
        const s = new URL(site);
        if (u.hostname.replace(/^www\./, '') !== s.hostname.replace(/^www\./, '')) return '';
      }
      return u.href;
    } catch { return ''; }
  }

  /**
   * Clamp whatever the model returned to something executable.
   * The planner is a designer, not a source of truth.
   */
  validate(plan, platform, { site = '', studio = false } = {}) {
    const rules = PLATFORM_RULES[platform] || PLATFORM_RULES.instagram;
    const tasks = Array.isArray(plan?.tasks) ? plan.tasks : [];

    const cleaned = [];
    let dailyTotal = 0;
    let videoTasks = 0;

    for (const t of tasks.slice(0, 5)) {
      const format = rules.formats.includes(t.format) ? t.format : rules.formats[0];

      // Video is slow and costs ~10x an image; one such task is plenty.
      if (format === 'video' && ++videoTasks > 1) continue;

      let timesPerDay = Math.max(1, Math.min(Number(t.timesPerDay) || 1, 4));
      let times = Array.isArray(t.times) && t.times.length ? t.times : ['09:00'];
      // times must line up with timesPerDay or the scheduler fires the wrong number.
      times = times.filter((x) => /^\d{1,2}:\d{2}$/.test(x)).slice(0, timesPerDay);
      while (times.length < timesPerDay) times.push('09:00');
      timesPerDay = times.length;

      const days = Array.isArray(t.daysOfWeek) && t.daysOfWeek.length
        ? t.daysOfWeek.filter((d) => Number.isInteger(d) && d >= 0 && d <= 6)
        : [1, 2, 3, 4, 5];

      // Enforce the platform's combined daily ceiling, in the order proposed.
      const perDay = timesPerDay * (days.length / 7);
      if (dailyTotal + perDay > rules.maxTotalPerDay + 0.5) continue;
      dailyTotal += perDay;

      cleaned.push({
        name: this.sanitize(String(t.name || 'Untitled task'), { studio }).slice(0, 60),
        description: this.sanitize(String(t.description || ''), { studio }).slice(0, 300),
        angle: this.sanitize(String(t.angle || t.description || ''), { studio }).slice(0, 500),
        format,
        theme: String(t.theme || '').slice(0, 40),
        hookStyle: String(t.hookStyle || '').slice(0, 40),
        goal: String(t.goal || 'reach').slice(0, 40),
        linkUrl: this.sanitizeLink(t.linkUrl, site),
        cta: String(t.cta || '').slice(0, 40),
        schedule: { timesPerDay, times, daysOfWeek: days.length ? days : [1, 2, 3, 4, 5] },
      });
    }

    // With Studio, every set has a product video about twice a week: the most convincing thing it can post.
    if (studio && rules.formats.includes('video') && !cleaned.some((t) => t.format === 'video')) {
      cleaned.push({
        name: 'Product video',
        description: 'A short video of the product made from its own website screens',
        angle: 'Show one feature or workflow of the product from its real screens, a different one each time; when something is new on the site, show that.',
        format: 'video',
        theme: 'product',
        hookStyle: 'demo',
        goal: 'reach',
        linkUrl: this.sanitizeLink(site, site),
        cta: 'See it live',
        schedule: { timesPerDay: 1, times: ['11:00'], daysOfWeek: [2, 4] },
      });
    }

    return { tasks: cleaned, reasoning: plan?.reasoning || '' };
  }

  /**
   * Generate and persist a task set. Replaces any existing agent-made tasks
   * for this platform; tasks the user created by hand are left alone.
   */
  async generate({ userId, autopilotId = null, platform, brand, website = null, timezone = 'Asia/Kolkata', replace = true }) {
    if (!brand?.oneLiner && !(brand?.topicsAllowed || []).length) {
      return { success: false, error: 'No brand profile yet - crawl the website first.' };
    }

    const pages = (website?.pagesRead || []).map((p) => ({ url: p.url, title: p.title || p.label }));
    if (website?.url && !pages.some((p) => p.url === website.url)) pages.unshift({ url: website.url, title: 'Homepage' });
    const performance = await this.performanceSummary({ userId, autopilotId, platform }).catch(() => null);
    const studio = process.env.STUDIO_ENABLED === 'true' && Boolean(website?.url);

    let plan;
    try {
      plan = await this.llm.chatJSON(
        [
          { role: 'system', content: this.systemPrompt(SYSTEM_PROMPT, platform, { studio }) },
          { role: 'user', content: this.buildPrompt(brand, platform, { pages, performance }) },
        ],
        { temperature: 0.6, fallback: null }
      );
    } catch (err) {
      return { success: false, error: `Task planning failed: ${err.message}` };
    }

    const { tasks, reasoning } = this.validate(plan, platform, { site: website?.url || '', studio });
    if (tasks.length === 0) {
      return { success: false, error: 'The planner produced no usable tasks.' };
    }

    if (replace) {
      await AutopilotTask.deleteMany({ userId, ...(autopilotId ? { autopilotId } : {}), platform, source: 'agent' });
    }

    const created = [];
    for (const t of tasks) {
      const doc = new AutopilotTask({
        userId,
        autopilotId,
        platform,
        ...t,
        schedule: { ...t.schedule, timezone },
        source: 'agent',
        enabled: true,
      });
      doc.assignJitter();
      doc.scheduleNextRun();
      await doc.save();
      created.push(doc);
    }

    console.log(`🗂️  [TASKS] ${created.length} task(s) generated for ${userId} on ${platform}`);
    return { success: true, tasks: created, reasoning };
  }
  /**
   * The platform agent's read on the current task set: what is working, what
   * is not, and concrete patches the UI can apply to individual tasks.
   */
  async review({ userId, autopilotId = null, platform, brand, website = null }) {
    const tasks = await AutopilotTask.find({ userId, ...(autopilotId ? { autopilotId } : {}), platform, kind: { $ne: 'daily_plan' } }).sort({ createdAt: 1 });
    const performance = await this.performanceSummary({ userId, autopilotId, platform }).catch(() => null);
    const spec = PlatformDefaults.get(platform);
    const rules = PLATFORM_RULES[platform] || PLATFORM_RULES.instagram;

    const taskLines = tasks.map((t) =>
      `- id=${t.taskId} "${t.name}" [${t.format}] ${t.schedule?.timesPerDay}x/day at ${(t.schedule?.times || []).join(',')} on days ${(t.schedule?.daysOfWeek || []).join('')} | enabled=${t.enabled} | runs=${t.runCount || 0} posts=${t.postsCreated || 0} failures=${t.consecutiveFailures || 0}${t.linkUrl ? ` | link=${t.linkUrl}` : ''}\n    angle: ${t.angle || t.description}`);

    const user = `## Platform
${spec.name}. ${rules.guidance}
Allowed formats: ${rules.formats.join(', ')}. Daily ceiling across all tasks: ${rules.maxTotalPerDay}.

## Company
${brand?.companyName || ''} - ${brand?.oneLiner || ''}
Audience: ${brand?.targetAudience || 'n/a'}. Tone: ${brand?.tone || 'n/a'}.
Site: ${website?.url || 'n/a'}

## Current tasks
${taskLines.join('\n') || '(none yet)'}

## Performance
${this.formatPerformance(performance)}

Review the task set.`;

    let out;
    try {
      out = await this.llm.chatJSON(
        [
          { role: 'system', content: this.systemPrompt(REVIEW_PROMPT, platform, { studio: process.env.STUDIO_ENABLED === 'true' && Boolean(website?.url) }) },
          { role: 'user', content: user },
        ],
        { temperature: 0.4, fallback: null }
      );
    } catch (err) {
      return { success: false, error: `The agent could not review the tasks: ${err.message}` };
    }
    if (!out) return { success: false, error: 'The agent returned nothing usable.' };

    const ids = new Set(tasks.map((t) => t.taskId));
    const suggestions = (Array.isArray(out.suggestions) ? out.suggestions : []).slice(0, 5).map((sg) => {
      const patch = sg.patch && typeof sg.patch === 'object' ? sg.patch : {};
      const clean = {};
      if (patch.schedule && typeof patch.schedule === 'object') clean.schedule = patch.schedule;
      if (patch.format && rules.formats.includes(patch.format)) clean.format = patch.format;
      if (typeof patch.enabled === 'boolean') clean.enabled = patch.enabled;
      if ('linkUrl' in patch) clean.linkUrl = this.sanitizeLink(patch.linkUrl, website?.url || '');
      if (patch.cta) clean.cta = String(patch.cta).slice(0, 40);
      return {
        taskId: ids.has(sg.taskId) ? sg.taskId : null,
        title: this.sanitize(String(sg.title || '')).slice(0, 80),
        reason: this.sanitize(String(sg.reason || '')).slice(0, 300),
        patch: clean,
      };
    });

    return {
      success: true,
      agent: AGENT_NAMES[platform] || 'growth agent',
      metricsAvailable: performance?.metricsAvailable ?? true,
      summary: this.sanitize(String(out.summary || '')),
      insights: (Array.isArray(out.insights) ? out.insights : []).slice(0, 6).map((i) => this.sanitize(String(i))),
      suggestions,
      performance,
    };
  }
}

module.exports = TaskPlanner;
module.exports.PLATFORM_RULES = PLATFORM_RULES;
